url: "http://babyfoodrecipes.in"
pygments: true
exclude: [bin, Gemfile, Gemfile.lock]
markdown: kramdown
permalink: pretty
paginate: 10
excerpt_separator: <!--more--> 

kramdown:
  entity_output: symbolic
